### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by wangly** [Netonline2016/k8s-ansible#1]
TASK [master : Create clusterrolebinding for kubelet-bootstrap user and system:node-bootstrap clusterrole] *********************************************************************************************
skipping: [172.27.0.6]
skipping: [172.27.16.14]
fatal: [172.27.0.15]: FAILED! => {"changed": true, "cmd": "kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap", "delta": "0:00:00.124801", "end": "2018-11-29 15:51:37.317149", "msg": "non-zero return code", "rc": 1, "start": "2018-11-29 15:51:37.192348", "stderr": "Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")", "stderr_lines": ["Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")"], "stdout": "", "stdout_lines": []}
仅修改了ca信息部分，安装提示如上。到master节点执行kubectl，提示如下：
kubectl get node
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes"

请问您是否有相关问题经验？

**Comment by wangly** [comment]
已解决，原因：1. 项目中playbooks/roles/plugins/templates/coredns/coredns-cm.yaml.j2存在注释，导致执行失败；2. 修改后，重试，证书全部重新生成了，但项目中所有组件服务没有重启，导致认证失败。
解决：1. 去掉coredns-cm.yaml.j2文件中的注释；2. 所有使用到证书的服务，start改为restart。

**Comment by Netonline2016** [comment]
@wangly 感谢指正。
因在实际验证环境中用到了coredns的`host`插件，提交到github中将此部分做了注释，但因为coredns-cm.yaml.j2中注释部分也存在变量调用，而这部分被引用的变量在`~/k8s-ansible/inventory/group_vars/all`中也被注释了，所以会导致第一个问题。
目前已更正：保留了`host`插件的格式，放开`~/k8s-ansible/inventory/group_vars/all`的部分注释。
